### ISSUE TITLE
Convert to Midi Device?

### ISSUE THREAD

**Issue by Zetalia** [zsteinkamp/m4l-ChiasticSlide#1]
Hello Zack,

first of all i want to thank you for your genious devices, i enjoy using them a lot.
With Chiastic Slide i tried to convert it to a midi device in max but seems to be more complicated than i thought.
Do you have plans to make this possible?

**Comment by zsteinkamp** [comment]
Oh hey @Zetalia! Thank you for writing in here. :) I appreciate it.

As a MIDI device, do you see it as controlling a velocity coefficient for the different MIDI chains, or some other parameter?

**Comment by Zetalia** [comment]
Hello Zach, i was trying to fast crossfade between two midi echoes with different timings.

**Comment by zsteinkamp** [comment]
Ok thanks for the detail. 
So you're looking for a device to act on the MIDI notes, and not the audio output of MIDI-controlled instruments then right?

An example... You have a MIDI Effect Rack in Ableton. That rack has two chains. Each chain has a MIDI echo device. One note comes into the rack, many notes exit each chain in the rack.

How would you like to crossfade these MIDI Effect chains? Is it through MIDI note velocity or some other mechanism you have in mind?

**Comment by zsteinkamp** [comment]
Closing this device due to inactivity. @Zetalia if you have an answer to the above, let me know.
