### ISSUE TITLE
The direction wrap around behaviour cases issues with automation

### ISSUE THREAD

**Issue by thomasf** [zsteinkamp/m4l-ChiasticSlide#3]
When automating the direction and you reach min or max value the direction parameter becomes disabled in live because max changes the value.

And thanks for all the incredible devices, I discovered them today!

**Comment by thomasf** [comment]
btw. I instinctively try to use the jsui window to drag the direction around from time to time so maybe that one could do the endless rotation instead of the rotation dial.

**Comment by zsteinkamp** [comment]
Thanks @thomasf! 

Looks like I got too excited and rushed out the endless knob before I could really put it through its paces.
I did figure out how to get the automation state of the knob and disable the endless stuff when it's automated.

I also want to interact with the visualization, so I'll learn some [jsui] mouse events stuff now :)

Thank you!
