### ISSUE TITLE
pot mode for direction knob

### ISSUE THREAD

**Issue by Luke-kb** [zsteinkamp/m4l-ChiasticSlide#5]
Hey @zsteinkamp - I'm really enjoying the new endless encoder feature you added in v7. However, I've found that in some cases I actually would prefer "potentiometer-style" like it was previously. Would it be hard to create a toggle to switch between the two modes?
My current workaround atm is to limit the direction values between 1 and 359 for midi mapped pot

**Comment by zsteinkamp** [comment]
Glad to have your ideas here @Luke-kb!

I'm nearly done adding a mode toggle and will release it today.

Thoughts on this layout?

![Screenshot 2024-12-10 at 7 47 12 AM](https://github.com/user-attachments/assets/bfa2e806-96df-4155-b7e3-c545f37aa012)

(I also fixed the "Min Vol" display to be accurate to what happens beyond the set width.)

**Comment by Luke-kb** [comment]
looks great 👍

**Comment by zsteinkamp** [comment]
Thanks :) Just published v9.
https://github.com/zsteinkamp/m4l-ChiasticSlide/releases/tag/v9
