### ISSUE TITLE
auto-set the width to match no. of audio sources

### ISSUE THREAD

**Issue by Luke-kb** [zsteinkamp/m4l-ChiasticSlide#6]
Hey @zsteinkamp! As always, loving the plugin. The more I use it, the more ideas I get 😄 
in your [comment](https://github.com/zsteinkamp/m4l-ChiasticSlide/issues/2#issuecomment-2509020300) from a previous issue - you mentioned the calculation to get a nice width per audio source. 

I'm finding that 99% of the time I want this kind of width with the constant power setting. What would be really handy would be for this calculation to occur either as part of the "rescan" function button click, or even better - automatically when the no. of tracks changes within the instrument rack. A separate button could also work too. Keen to hear your thoughts :)

**Comment by zsteinkamp** [comment]
You keep reading my mind. I think a few of "Auto" or preset buttons may be good? Doing it on initial setup or rescan seems good (if possible) but I think doing it on track population changes may be annoying in some situations.

I'll try these first:
width = ((360 / n) * n-1), curve = 1
width = ((360 / n) * 3), curve = 0.32, linear power
width = ((360 / n) * 3), curve = 0.64, constant power

Other thoughts?

**Comment by Luke-kb** [comment]
working excellent for me 👍
